In [4]:
#matrix operations(using vectorization) and transformation using python and svd using python
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
add=a+b
print("additon",add)
sub=a-b
print("\nsubtraction ",sub)
multi=a*b
print("\nmultiplication(element wise)",multi)
#matrix multiplication
F=np.dot(a,b)#ora@b
a_transpose=a.T
print("\nmatrix mul


additon [[ 6  8]
 [10 12]]
subtraction  [[-4 -4]
 [-4 -4]]
multiplication  [[ 5 12]
 [21 32]]


In [6]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_components=2
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("original matrix:")
print(X)
print("\nReconstructed matrix(with reduced dimensions):")
print(X_reconstructed)

original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
